/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 16 22:21:14 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.osu.cs362.MyTreeNode;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MyTreeNode_ESTest extends MyTreeNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MyTreeNode<String> myTreeNode0 = new MyTreeNode<String>("!N!C");
      MyTreeNode myTreeNode1 = myTreeNode0.getParent();
      myTreeNode1.addChild(myTreeNode0);
      MyTreeNode<Object> myTreeNode2 = new MyTreeNode<Object>((Object) "!N!C");
      MyTreeNode myTreeNode3 = myTreeNode2.getParent();
      List<MyTreeNode> list0 = (List<MyTreeNode>)myTreeNode0.getChildren();
      myTreeNode3.addChildren(list0);
      assertFalse(myTreeNode3.equals((Object)myTreeNode1));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object object0 = new Object();
      MyTreeNode<Object> myTreeNode0 = new MyTreeNode<Object>(object0);
      // Undeclared exception!
      try { 
        myTreeNode0.addChildren((List<MyTreeNode>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.MyTreeNode", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MyTreeNode<String> myTreeNode0 = new MyTreeNode<String>("");
      // Undeclared exception!
      try { 
        myTreeNode0.addChild((MyTreeNode) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("edu.osu.cs362.MyTreeNode", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MyTreeNode<String> myTreeNode0 = new MyTreeNode<String>("!N!C");
      MyTreeNode myTreeNode1 = myTreeNode0.getParent();
      List<MyTreeNode> list0 = (List<MyTreeNode>)myTreeNode0.getChildren();
      myTreeNode1.addChildren(list0);
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MyTreeNode<String> myTreeNode0 = new MyTreeNode<String>("`M");
      myTreeNode0.setData("`M");
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Object object0 = new Object();
      MyTreeNode<Object> myTreeNode0 = new MyTreeNode<Object>(object0);
      myTreeNode0.addChild(object0);
  }
}
